### ISSUE TITLE
optional message protocol 

### ISSUE THREAD

**Issue by laurentsifre** [ashottonoyan/FacebookFramework#1]
It took me some time to figure out that the optional message in FacebookDelegate needs to be implemented because you check that the delegate responds to the selector.

 [self.delegate respondsToSelector:@selector(fbAuthWindowWillShow:)]

This is confusing since it is specified as optional.

Anyway this works great for me now so thanks a lot.

**Comment by ashottonoyan** [comment]
Hi 
Thanks for your contribution

Yeah, really there is a confusion.
I will leave fbAuthWindowWillShow: as optional, 
but I'll change this part of code :

``` objc
if (self.delegate && [self.delegate respondsToSelector:@selector(fbAuthWindowWillShow:)] && ![self.window isVisible]) {
    [self.window center];
    [_window makeKeyAndOrderFront:nil];
    [self.delegate fbAuthWindowWillShow:self];
}
```

with this :

``` objc
if (self.delegate && [self.delegate respondsToSelector:@selector(fbAuthWindowWillShow:)] && ![self.window isVisible]) {
    [self.delegate fbAuthWindowWillShow:self];
}
[self.window center];
[_window makeKeyAndOrderFront:nil];
[NSApp activateIgnoringOtherApps:YES];
```

due to `[NSApp activateIgnoringOtherApps:YES];` is required for showing facebook auth window.
